server:
  port: 2000

spring:
  application:
    name: one-team-zuul
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:2338

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: localhost

# zuul \u805A\u5408\u670D\u52A1
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: one-team-uap