server:
  port: 8810

spring:
  application:
    name: one-team-servie-user
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:9999
  datasource:
    druid:
      url: jdbc:mysql://185.45.114.190:3306/one_team?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: shin
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.ideashin.one.team.service.user.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8866/eureka/,http://${eureka.instance.hostname}:8867/eureka/,http://${eureka.instance.hostname}:8868/eureka/
  instance:
    hostname: 185.45.114.190

# health健康查看
management:
  endpoint:
    health:
      show-details: always # 开启所有的Health监控数据:
  endpoints:
    web:
      exposure:
        include: health, info # 开启了info和health两个端点