server:
  port: 8910

spring:
  application:
    name: one-team-api-user
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/,http://${eureka.instance.hostname}:2334/eureka/,http://${eureka.instance.hostname}:2335/eureka/
  instance:
    hostname: 185.45.114.190

# health健康查看
management:
  endpoint:
    health:
      show-details: always # 开启所有的Health监控数据:
  endpoints:
    web:
      exposure:
        include: health, info # 开启了info和health两个端点