spring:
  application:
    name: one-team-admin
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411

server:
  port: 2338

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: localhost

# health健康查看
management:
  endpoint:
    health:
      show-details: always # 开启所有的Health监控数据:
  endpoints:
    web:
      exposure:
        include: ["health", "info"] # 开启了info和health两个端点