spring:
  application:
    name: one-team-zipkin

# \u9ED8\u8BA4\u7AEF\u53E3
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: localhost
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411
# 设置是否应自动定时服务器请求
management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
