# config-server默认的端口就是8888，不能修改
# 修改需要额外新建一个bootstrap.properties里面server.port进行配置，此配置有限加载
server:
  port: 8888

spring:
  application:
    name: one-team-config
#  # 本地路径
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/resposity
#  git路径
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/IDEAShin/one-team.git
          search-paths: one-team-config/src/main/resources/respo
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:2338

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: 47.56.157.210
