server:
  port: 2337

spring:
  application:
    name: one-team-mcs
  zipkin:
    base-url: http://${eureka.instance.hostname}:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:2333/eureka/
  instance:
    hostname: localhost